chore: Optimize build script

diff --git a/build_quartz_pages b/build_quartz_pages
--- a/build_quartz_pages
+++ b/build_quartz_pages
@@ -1,19 +1,35 @@
 #!/bin/bash
 
 echo "----- STARTING to build quartz pages ------"
-printenv | grep "QUARTZ_CONTENT_REPOSITORY_URL"
 
-cd $(mktemp -d) && \
-git clone $QUARTZ_CONTENT_REPOSITORY_URL && \
-cd * && \
-cp -Rp . /app/quartz/content && \
-rm -r .
-cd /app/quartz && \
-npx quartz build -o current_quartz_build && \
-rm -rf /var/www/quartz/public/* && \
-cp -r current_quartz_build/* /var/www/quartz/public/ && \
-chown -R www-data:www-data /var/www/quartz/public && \
-ls /var/www/quartz/public && \
-echo "----- SUCCESS: Built quartz pages to /var/www/quartz/public/* ------" && exit 0
+function get_contents() {
+    URL=$1
+    REPO_DIR=$2
+    CONTENT_DIR=$3
 
-echo "----- FAILED: To build quartz pages ------" && exit 1
+    if [[ "$(ls $REPO_DIR | wc -l)" -eq 0 ]]; then
+        echo "Repository doesnt exist yet --> cloning $URL"
+        git clone $URL $REPO_DIR
+    else 
+        echo "Repository exists --> pulling $QUARTZ_CONTENT_REPOSITORY_URL"
+        cd $REPO_DIR && git pull
+    fi
+
+    cp -Rp $REPO_DIR/* $CONTENT_DIR
+}
+
+function build_contents() {
+    QUARTZ_DIR=$1
+    OUTPUT_DIR=$2
+
+    cd $QUARTZ_DIR && \
+    npx quartz build -o current_quartz_build && \
+    cp -TR current_quartz_build $OUTPUT_DIR  && \
+    chown -R www-data:www-data $OUTPUT_DIR && \
+    echo "----- SUCCESS: Built quartz pages to $OUTPUT_DIR ------" && exit 0
+    echo "----- FAILED: To build quartz pages ------" && exit 1
+}
+
+get_contents $QUARTZ_CONTENT_REPOSITORY_URL /app/repository /app/quartz/content
+build_contents /app/quartz /var/www/quartz/public
+
